### PR TITLE
v2.3.2

### LINKED ISSUE #178: Pyzeebe will never time out a connection to a gateway with problems
**Describe the bug**
If the gateway fails in a certain way, while a connection has been opened to it, Pyzeebe will not time out.

The issue applies both to the client, and the worker.

For the worker, the issue is noticed by it hanging, if it experience loss of connectivity to gateway.

**To Reproduce**

Start the gateway and brokes (use https://github.com/camunda-community-hub/zeebe-docker-compose/blob/0.26.0/standalone-gateway/docker-compose.yml) – don't run any workers against this cluster.

```console
docker-compose up -d
```

In a second terminal, run the following code:

```py
import logging
from pyzeebe import ZeebeClient
logging.basicConfig(level=logging.DEBUG, format="%(asctime)s %(levelname)s [%(thread)d|%(threadName)s] %(filename)s:%(lineno)d: %(message)s")


zeebe_client = ZeebeClient(hostname="localhost", port=26500)
zeebe_client.deploy_workflow("tests/integration/test.bpmn")
try:
    workflow_instance_key, workflow_result = zeebe_client.run_workflow_with_result(
        bpmn_process_id="test",
        timeout=10000
    )
    logging.info("Result: %s", workflow_result)
except Exception as e:
    logging.exception("Run failed")
```

After a few seconds, pause the broker, using 

```console
docker-compose pause gateway
```

What you'll see is that the client waits forever (actually 2 hours) since the broker has gone down:

```
2021-06-25 14:11:20,716 DEBUG [123145476907008|Thread-2] zeebe_adapter_base.py:51: Grpc channel connectivity changed to: ChannelConnectivity.IDLE
2021-06-25 14:11:20,716 DEBUG [123145476907008|Thread-2] zeebe_adapter_base.py:55: Connected to localhost:26500
2021-06-25 14:11:20,716 DEBUG [123145476907008|Thread-3] zeebe_adapter_base.py:51: Grpc channel connectivity changed to: ChannelConnectivity.CONNECTING
2021-06-25 14:11:20,716 DEBUG [123145476907008|Thread-3] zeebe_adapter_base.py:61: Connecting to localhost:26500.
2021-06-25 14:11:20,718 DEBUG [123145476907008|Thread-4] zeebe_adapter_base.py:51: Grpc channel connectivity changed to: ChannelConnectivity.READY
2021-06-25 14:11:20,718 DEBUG [123145476907008|Thread-4] zeebe_adapter_base.py:55: Connected to localhost:26500
```

The reason being that the `timeout` argument is for the server side, and not the client-side.  ​

**Expected behavior**

If connection to the gateway is lost, Pyzeebe should detect this and throw an error (or retry connection).

**Version**

- Pyzeebe: 0.26.4
- Zeebe: 0.26.0
​
**Additional context**

- https://github.com/grpc/grpc/blob/0e20a5fce8e53510255fa1a5199544a86ebfcd8e/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L65-L70
    - By default, the gRPC client will wait for 2 hours (`DEFAULT_SERVER_KEEPALIVE_TIME_MS`) before trying to check if the server is still up 

This has been solved in the official clients:

- https://github.com/camunda-cloud/zeebe/issues/3368
- https://github.com/camunda-cloud/zeebe/pull/3487

node.js:

- https://github.com/camunda-community-hub/zeebe-client-node-js/blob/2b1312dfed027d942a04c8ec6b0eaac3591aee57/src/lib/GrpcClient.ts#L227-L291

C#:

- https://github.com/camunda-community-hub/zeebe-client-csharp/blob/af5ed6bfb20c353c5e27a362e8778302c7b22e4c/Client/ZeebeClient.cs#L75-L92

### PR DESCRIPTION
**Pull request by JonatanMartens**
Fix #178

## Changes

- Make sure pyzeebe times out after 45 seconds instead of two hours - see #178 

### New Features

none

### Deprecations

none

## Checklist

- [x] Unit tests
- [ ] Documentation

## References

Fixes #178

### CODE REVIEW

**Review by kbakk — APPROVED** [review]

**Comment by JonatanMartens** [comment]
Hey @celanthe we can't merge this because it requires the commits to be signed. Was this changed under camunda-community-hub?

**Comment by kbakk** [comment]
@JonatanMartens could it be that the repo is configured with branch protection rules? 
image

(Under `https://github.com/<org>/<repo>/settings/branches`)

**Comment by celanthe** [comment]
Hi @kbakk and @JonatanMartens -- I see that this branch requires commits to be signed. This isn't something that we changed in the Community Hub, no. Is this something that might have been configured on this repository? You may be able ot change it in the Settings. 

Would you like me to go ahead and merge this PR? [I can, as I am an Organization admin]. If so, please let me know. I am happy to do so. 

Thank you so much!

**Comment by JonatanMartens** [comment]
> Would you like me to go ahead and merge this PR? [I can, as I am an Organization admin]. If so, please let me know. I am happy to do so.

Yes, that would be great!

> Hi @kbakk and @JonatanMartens -- I see that this branch requires commits to be signed. This isn't something that we changed in the Community Hub, no. Is this something that might have been configured on this repository? You may be able ot change it in the Settings.

It seems I do not have access to the settings. Is there any way I can get back permissions to change these?

**Comment by celanthe** [comment]
Hi @JonatanMartens! I bumped your permissions up to Admin for this repositoru! Please let me know if you have the ability to merge PRs now. :) 

I'll go ahead and merge this in the meantime!

**Pull request merged**
