### PR TITLE
feat: generate python class interface from protobuf

### LINKED ISSUE #475: Generate python class interface files from protobuf
**Is your feature request related to a problem? Please describe.**

The pyzee internals are using unknown imports and some non proto Stub generated type classes.
The package `zeebe-grpc` does not provide python class files from protobuf. And uses older versions of grpcio and protobuf.

**Describe the solution you'd like**
Generate the protobuf stubs and interface (.pyi) for Python ourselfs and remove the dependency from zeebe-grpc.
This also enhances type hints because of the usage of the protobuf generated interface for pyzeebe.

There is also the option to create mypy types from protobuf.

`python -m grpc_tools.protoc --proto_path=. --python_out=. --grpc_python_out=. --pyi_out=. ./pyzeebe/proto/gateway.proto`

For this we need to add the following requirements:
1. grpcio = ">=1.66.0"
2. grpcio-tools = ">=1.66.0"
3. protobuf = ">=5.27.2,<5.28.0"

**Additional context**

https://grpc.io/docs/languages/python/basics/#generating-client-and-server-code
https://mypy.readthedocs.io/en/stable/stubs.html

### PR DESCRIPTION
**Pull request by felicijus**
Description of PR...

## Changes

- add `proto` directory for protobuf and the generated stub and interface files
- remove `zeebe-grpc`

### New Features *(required)*

Latest version of [Zeebe API (GRPC) proto](https://github.com/camunda/camunda/blob/main/zeebe/gateway-protocol/src/main/proto/gateway.proto).

1. grpcio = ">=1.66.0"
2. grpcio-tools = ">=1.66.0"
3. protobuf = ">=5.27.2,<5.28.0
4. types-protobuf
5. mypy-protobuf

Command for generation with .pyi:
```shell
python -m grpc_tools.protoc --proto_path=. --python_out=. --grpc_python_out=. --pyi_out=. ./pyzeebe/proto/gateway.proto
```
or with mypy
```
python -m grpc_tools.protoc --proto_path=. --python_out=. --grpc_python_out=. --mypy_out . --mypy_grpc_out . ./pyzeebe/proto/gateway.proto
```

### Deprecations *(required)*

Package `zeebe-grpc` is no longer used. And is removed rom `pyproject.toml`
Removed all traces of zeebe-grpc and exchanged for the new stubs and interface files generated from `.proto`

### Enhancements *(optional)*

Now `.pyi` interface file is available and supports better type hints.

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References

https://grpc.io/docs/languages/python/basics/#generating-client-and-server-code
https://mypy.readthedocs.io/en/stable/stubs.html

Resolves #475

### CODE REVIEW

**Comment by dimastbk** [comment]
Hi. Why not fix it in `zeebe-grpc`?

**Comment by felicijus** [comment]
The reasoning was that we could track changes more closely if we maintained it ourselves, which I think is even more important if we use the mypy option.

Secondly, it's the interfaces for connecting to zeebe that we are programming against, especially when using typing. My understanding is that the interface belongs in the package itself.

By the way, which version do you prefer, mypy or just the pyi?

**Comment by dimastbk** [comment]
I think this package shouldn't be a part of pyzeebe:
1. some people may want to use only grpc stubs without worker;
2. `zeebe-grpc` should have own release cycle.

**Comment by felicijus** [comment]
Hello,
just looked into older stuff.

1. You can still to that even with pyzeebe, stubs are still there.
2. Yes it should, but if you already do releases (way more often thaan (zeebe-grpc) why not automate the stub file creation plus mypy for types for every release, meaning no upstream dependency and always the latest interface?

Kind Regards
Felix

**Pull request closed without merging**
